pipeline {
    agent { label 'frontend' }
    environment {
        SERVER_CREDENTIALS = 's3-access'
        WEBHOOK_URL = credentials('DiscordWebhookAT')
        BUCKET = 'oleksandr-team-bucket'
        API_URL = credentials('url_back_at')
        REGION = 'eu-central-1'
        FRONTEND_ACCESS_KEY = credentials('at_frontend_access_key')
        FRONTEND_SECRET_KEY = credentials('at_frontend_secret_key')
    }
    stages {
        stage('clone') {
            steps {
                git branch: 'dev', url: 'https://github.com/Team-Alexander/frontend.git'
            }
        }
        stage('build') {
            steps {
                sh '''
                export REACT_APP_API_URL=${API_URL}
                export BUCKET="oleksandr-team-backend"
                export S3_ACCESS_KEY=${FRONTEND_ACCESS_KEY}
                export S3_SECRET_KEY=${FRONTEND_SECRET_KEY}
                export S3_REGION=${REGION}

                npm install 
                npm run build
                chmod -R 755 ./build/*
                '''
            }
        }
        stage('deploy') {
            steps {
                sh '''
                    ssh -i "/home/jenkins/.ssh/slave-SoftServe2023" oleksandr-team@10.0.1.250 "rm -rf /var/www/oleksandr-team/html/*"
                    scp -i "/home/jenkins/.ssh/slave-SoftServe2023" -rp ./build/* oleksandr-team@10.0.1.250:/var/www/oleksandr-team/html/
                '''
            }
        }
        stage('upload to s3') {
            steps {
                withAWS(credentials: "${SERVER_CREDENTIALS}", region: 'eu-central-1') {
                    script {
                        println 'Uploading artifacts...'
                        sh '''
                        cd ./build/
                        tar -cvzf "build-${BUILD_NUMBER}.tar.gz" ./*
                        '''
                        s3Upload(file: "./build/build-${BUILD_NUMBER}.tar.gz", bucket: "${BUCKET}", path:"frontend/dev")
                    }
                }
            }
        }
    }
    post {
        always {
            discordSend description: "Jenkins pipeline build: ${currentBuild.currentResult}\nBuild log: ${BUILD_URL}consoleText",
                link: env.BUILD_URL,
                result: currentBuild.currentResult,
                title: JOB_NAME,
                webhookURL: "${env.WEBHOOK_URL}"
            sh 'rm -rf ./*'
        }
    }
}
