pipeline {
    agent none
    environment {
        SERVER_CREDENTIALS = 's3-access'
        WEBHOOK_URL = credentials('DiscordWebhookAT')
        BUCKET = 'oleksandr-team-bucket'
        REGION = 'eu-central-1'
        BACKEND_ACCESS_KEY = 'at_backend_access_key'
        BACKEND_SECRET_KEY = 'at_backend_secret_key'
    }
    stages {
        stage('Build') {
            agent { label 'java && jdk-17' }
            steps {
                git branch: 'dev', url: 'https://github.com/Team-Alexander/backend.git'
                sh '''
                    export JAVA_HOME="/lib/jvm/jdk-17"

                    export BUCKET="oleksandr-team-backend"
                    export S3_ACCESS_KEY=$(aws ssm get-parameter --region ${REGION} --name ${BACKEND_ACCESS_KEY} --with-decryption --query Parameter.Value --output text)
                    export S3_SECRET_KEY=$(aws ssm get-parameter --region ${REGION} --name ${BACKEND_SECRET_KEY} --with-decryption --query Parameter.Value --output text)

                    chmod 744 ./mvnw
                    rm -f .env
                    echo "SPRING_PROFILES_ACTIVE=prod" >> .env
                    ./mvnw clean package
                    cp ./target/UpTalentBackend*.jar ./UpTalentBackend-${BUILD_NUMBER}.jar
                '''
                withAWS(credentials: "${SERVER_CREDENTIALS}", region: "${REGION}") {
                    script {
                        s3Upload(file: "./UpTalentBackend-${BUILD_NUMBER}.jar", bucket: "${BUCKET}", path:"backend/UpTalentBackend-${BUILD_NUMBER}.jar")
                    }
                }
                sh 'rm ./UpTalentBackend-${BUILD_NUMBER}.jar'
            }
        }
        stage('Deploy') {
            agent { label 'java && target' }
            steps {
                withAWS(credentials: "${SERVER_CREDENTIALS}", region: "${REGION}") {
                    script {
                        s3Download(file:"./UpTalentBackend-${BUILD_NUMBER}.jar", bucket:"${BUCKET}", path:"backend/UpTalentBackend-${BUILD_NUMBER}.jar")
                    }
                }
                sh '''
                    sudo systemctl stop uptalentbackend || true
                    chmod 755 ./backend/install-systemd-service.sh
                    ./backend/install-systemd-service.sh
                    mv -f ./UpTalentBackend-${BUILD_NUMBER}.jar ~/UpTalentBackend.jar
                    sudo systemctl enable uptalentbackend --now
                '''
            }
        }
    }
    post {
        always {
            discordSend description: "Status: `${currentBuild.currentResult}`\nBuild log: ${BUILD_URL}consoleText",
                link: env.BUILD_URL,
                result: currentBuild.currentResult,
                title: JOB_NAME,
                webhookURL: "${env.WEBHOOK_URL}"
        }
    }
}